--!strict


local CharacterConfig = {}

CharacterConfig.WalkSpeed    = 14
CharacterConfig.RunSpeed     = 24
CharacterConfig.JumpPower    = 50

CharacterConfig.DashForce    = 80
CharacterConfig.DashDuration = 0.18
CharacterConfig.DashCooldown = 0.6

CharacterConfig.RollForce    = 60
CharacterConfig.RollDuration = 0.35
CharacterConfig.RollIFrames  = 0.25

CharacterConfig.DoubleTapWindow = 0.30

return CharacterConfig
